services:
  nginx:
    image: nginx
    networks:
      - nginx-application-net
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/sites-available/betest:/etc/nginx/sites-available/default
      - /etc/nginx/sites-available/betest:/etc/nginx/sites-enabled/default

  application:
    image: ${BACKEND_APP_IMAGE_NAME}
    networks:
      - nginx-application-net
    ports:
      - "8080:8080"
    environment:
      BACKEND_TEST: ${BACKEND_TEST}
    restart: always
    container_name: backend-test

networks:
  nginx-application-net:
