services:
  nginx:
    image: nginx
    depends_on:
      - application
    networks:
      - nginx-application-net
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/conf.d/custom.conf:/etc/nginx/conf.d/custom.conf

  application:
    image: ${BACKEND_APP_IMAGE_NAME}
    networks:
      - nginx-application-net
    ports:
      - "8080:8080"
    environment:
      BACKEND_TEST: ${BACKEND_TEST}
    restart: always
    container_name: backend-test

networks:
  nginx-application-net:
